# Auto-generated by scripts/setup.sh -- `source` this in every new shell.
# If RISCV_TOOLS_DIR is already set (e.g. by CI), use it; otherwise default.
export RISCV_TOOLS_DIR="${RISCV_TOOLS_DIR:-$HOME/riscv-tools}"
export RISCV_TOOLCHAIN="$RISCV_TOOLS_DIR/xpack-riscv-none-elf-gcc-14.2.0-3"
export PATH="$RISCV_TOOLCHAIN/bin:$RISCV_TOOLS_DIR/spike/bin:$HOME/.local/bin:$PATH"
export RISCV_PREFIX="riscv-none-elf-"
export RISCV_GCC="${RISCV_PREFIX}gcc"
export RISCV_OBJCOPY="${RISCV_PREFIX}objcopy"
export SPIKE_PATH="$RISCV_TOOLS_DIR/spike/bin"
