#!/usr/bin/env bash
# -----------------------------------------------------------------------------
# One-time environment setup. Idempotent -- safe to re-run.
#
# Installs, in order:
#   1. Verilator + build deps        (apt)
#   2. Python deps                   (pip, pinned via requirements.txt)
#   3. RISC-V GCC cross toolchain    (prebuilt tarball, NOT built from source)
#   4. Spike, the golden ISA sim     (built from source -- ~5 min)
#   5. riscv-arch-test suite         (cloned by riscof)
#
# Step 3 matters: building riscv-gnu-toolchain from source takes 1-3 HOURS and
# eats ~30 GB. Do not do that. Use the prebuilt release.
#
# Usage:  ./scripts/setup.sh
#         source scripts/env.sh      # in every new shell afterwards
# -----------------------------------------------------------------------------
set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
TOOLS_DIR="${RISCV_TOOLS_DIR:-$HOME/riscv-tools}"
mkdir -p "$TOOLS_DIR"

log() { printf '\n\033[1;34m==> %s\033[0m\n' "$*"; }

# -----------------------------------------------------------------------------
log "1/5  System packages"
# -----------------------------------------------------------------------------
sudo apt-get update -qq
sudo apt-get install -y \
    build-essential git curl wget \
    verilator gtkwave \
    device-tree-compiler \
    python3 python3-pip python3-venv \
    autoconf automake autotools-dev libmpc-dev libmpfr-dev libgmp-dev \
    gawk bison flex texinfo gperf libtool patchutils bc zlib1g-dev \
    libexpat-dev ninja-build cmake libglib2.0-dev libslirp-dev

verilator --version

# -----------------------------------------------------------------------------
log "2/5  Python packages"
# -----------------------------------------------------------------------------
pip3 install --user -r "$REPO_ROOT/requirements.txt" || \
  pip3 install --user --break-system-packages -r "$REPO_ROOT/requirements.txt"

# -----------------------------------------------------------------------------
log "3/5  RISC-V GCC toolchain (prebuilt)"
# -----------------------------------------------------------------------------
# The xPack builds are standalone, relocatable, and cover rv32 multilib.
# Check https://github.com/xpack-dev-tools/riscv-none-elf-gcc-xpack/releases
# for the current version and update XPACK_VER if this one has moved.
XPACK_VER="14.2.0-3"
XPACK_DIR="$TOOLS_DIR/xpack-riscv-none-elf-gcc-$XPACK_VER"

if [ ! -d "$XPACK_DIR" ]; then
  URL="https://github.com/xpack-dev-tools/riscv-none-elf-gcc-xpack/releases/download/v${XPACK_VER}/xpack-riscv-none-elf-gcc-${XPACK_VER}-linux-x64.tar.gz"
  echo "Downloading $URL"
  curl -fL "$URL" -o /tmp/xpack-riscv.tar.gz
  tar -xzf /tmp/xpack-riscv.tar.gz -C "$TOOLS_DIR"
  rm -f /tmp/xpack-riscv.tar.gz
else
  echo "Already present: $XPACK_DIR"
fi

# -----------------------------------------------------------------------------
log "4/5  Spike (riscv-isa-sim) -- the golden reference model"
# -----------------------------------------------------------------------------
SPIKE_SRC="$TOOLS_DIR/riscv-isa-sim"
SPIKE_PREFIX="$TOOLS_DIR/spike"

if [ ! -x "$SPIKE_PREFIX/bin/spike" ]; then
  [ -d "$SPIKE_SRC" ] || git clone --depth 1 \
      https://github.com/riscv-software-src/riscv-isa-sim.git "$SPIKE_SRC"
  mkdir -p "$SPIKE_SRC/build"
  pushd "$SPIKE_SRC/build" >/dev/null
    ../configure --prefix="$SPIKE_PREFIX" --enable-commitlog
    make -j"$(nproc)"
    make install
  popd >/dev/null
else
  echo "Already present: $SPIKE_PREFIX/bin/spike"
fi

# -----------------------------------------------------------------------------
log "5/5  Architectural test suite"
# -----------------------------------------------------------------------------
# riscof knows how to fetch the correct revision of riscv-arch-test itself,
# which is safer than pinning a URL here that may move.
if [ ! -d "$REPO_ROOT/riscv-arch-test" ]; then
  pushd "$REPO_ROOT" >/dev/null
    riscof --verbose info arch-test --clone
  popd >/dev/null
else
  echo "Already present: riscv-arch-test/"
fi

# -----------------------------------------------------------------------------
cat > "$REPO_ROOT/scripts/env.sh" <<EOF
# Auto-generated by scripts/setup.sh -- \`source\` this in every new shell.
export RISCV_TOOLS_DIR="$TOOLS_DIR"
export RISCV_TOOLCHAIN="$XPACK_DIR"
export PATH="\$RISCV_TOOLCHAIN/bin:$SPIKE_PREFIX/bin:\$HOME/.local/bin:\$PATH"
export RISCV_PREFIX="riscv-none-elf-"
export RISCV_GCC="\${RISCV_PREFIX}gcc"
export RISCV_OBJCOPY="\${RISCV_PREFIX}objcopy"
export SPIKE_PATH="$SPIKE_PREFIX/bin"
EOF

log "Done."
cat <<'EOF'

Next:
    source scripts/env.sh
    riscv-none-elf-gcc --version
    spike --help | head -3
    make lint && make unit

Add `source /path/to/repo/scripts/env.sh` to your ~/.bashrc so you do not have
to remember it.
EOF
